/**
 * Post-build prerender.
 *
 * Vite emits a single dist/index.html. That is fine for the browser — the app
 * reads location.pathname and renders the right view — but a crawler asking for
 * /academy would get the homepage's <title> and description, because the real
 * ones are only applied after React runs.
 *
 * So for every route we write a real HTML file at its real path, with that
 * page's metadata baked in. Two things fall out of this:
 *   1. Crawlers and WhatsApp read correct per-page metadata with zero JS.
 *   2. Real files mean no catch-all rewrite, so unknown URLs still 404 properly
 *      instead of silently returning the app shell (a soft 404).
 *
 * The page BODY is still client-rendered; this covers the metadata, which is
 * what search results and link previews actually display.
 *
 * Run automatically by `npm run build`.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'dist')

const { META, SITE_URL } = await import(join(ROOT, 'src/lib/seo.js'))
const { ROSTER } = await import(join(ROOT, 'src/data/fallen.js'))

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')

/** Swap the metadata in a copy of index.html. */
function render(shell, { title, description, canonical, noindex = false }) {
  let html = shell

  html = html.replace(/<title>[\s\S]*?<\/title>/, `<title>${esc(title)}</title>`)

  const setMeta = (attr, key, value) => {
    const re = new RegExp(`(<meta\\s+${attr}="${key}"\\s+content=")[^"]*(")`)
    if (re.test(html)) html = html.replace(re, `$1${esc(value)}$2`)
  }
  setMeta('name', 'description', description)
  setMeta('property', 'og:title', title)
  setMeta('property', 'og:description', description)
  setMeta('name', 'twitter:title', title)
  setMeta('name', 'twitter:description', description)

  // canonical + og:url are not in the source shell — inject them.
  const extra = [
    `<link rel="canonical" href="${esc(canonical)}" />`,
    `<meta property="og:url" content="${esc(canonical)}" />`,
    noindex ? '<meta name="robots" content="noindex" />' : '',
  ].filter(Boolean).join('\n    ')

  return html.replace('</head>', `  ${extra}\n  </head>`)
}

async function emit(path, html) {
  // "/" is dist/index.html; "/academy" is dist/academy/index.html.
  const outPath = path === '/' ? join(DIST, 'index.html') : join(DIST, path, 'index.html')
  await mkdir(dirname(outPath), { recursive: true })
  await writeFile(outPath, html, 'utf8')
  return outPath
}

const shell = await readFile(join(DIST, 'index.html'), 'utf8')

const urls = []
let count = 0

// ── Fixed routes ────────────────────────────────────────────────────────────
for (const meta of Object.values(META)) {
  const canonical = SITE_URL + (meta.path === '/' ? '/' : meta.path)
  await emit(meta.path, render(shell, { ...meta, canonical }))
  urls.push({ loc: canonical, priority: meta.path === '/' ? '1.0' : '0.8' })
  count++
}

// ── One page per fallen alum ────────────────────────────────────────────────
for (const entry of ROSTER) {
  const path = `/memorial/${entry.id}`
  const canonical = SITE_URL + path
  await emit(path, render(shell, {
    title: `${entry.n} ז״ל · היכל הזיכרון | חמש אצבעות`,
    description: `לזכרו של ${entry.n} ז״ל, בוגר תנועת חמש אצבעות שנפל במלחמת חרבות ברזל.`,
    canonical,
  }))
  urls.push({ loc: canonical, priority: '0.7' })
  count++
}

// ── Design preview — kept working, kept out of the index ────────────────────
await emit('/hero-concepts', render(shell, {
  title: 'Hero concepts · חמש אצבעות',
  description: 'תצוגת עיצוב פנימית.',
  canonical: SITE_URL + '/hero-concepts',
  noindex: true,
}))
count++

// ── Sitemap ─────────────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10)
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/prerender.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(({ loc, priority }) => `  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>${priority}</priority>
  </url>`).join('\n')}
</urlset>
`
await writeFile(join(DIST, 'sitemap.xml'), sitemap, 'utf8')

console.log(`prerendered ${count} pages · sitemap lists ${urls.length} URLs`)
